
name: micromamba
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:

  build_simple_with_pixi:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

      steps:
        ################################################################
        # SETUP
        ################################################################
        - name: Checkout repo
          uses: actions/checkout@v4
          with:
            fetch-depth: 0



        - uses: mamba-org/setup-micromamba@v2
          with:
            environment-file: dev-environment.yml
            init-shell: >-
              bash
            cache-environment: true
            post-cleanup: 'all'

        - name: download and patch box2d
          shell: bash -el {0}
          run: |
            mkdir -p deps/box2d &&
            cd deps &&
            curl -L -o box2d-commit.tar.gz https://github.com/erincatto/box2d/archive/f377034920c42a26cd498c0a0b1b2e9f2b064989.tar.gz &&
            tar --strip-components=1 -xvzf box2d-commit.tar.gz -C box2d &&
            cd box2d &&
            patch  -p1 -i ../box2d_patches/conditional_disable_cxx_operators.patch

        - name: build box2d
          shell: bash -el {0}
          run: |
            cmake -S deps/box2d -B deps/box2d/build \
              -DCMAKE_INSTALL_PREFIX=$(pwd)/.pixi/envs/build \
              -DCMAKE_INSTALL_LIBDIR=$(pwd)/.pixi/envs/build/lib \
              -DCMAKE_BUILD_TYPE=Release \`
              -DBUILD_SHARED_LIBS=ON \
              -DBOX2D_UNIT_TESTS=OFF \
              -DBOX2D_BENCHMARKS=OFF \
              -DBOX2D_SAMPLES=OFF
            cmake --build deps/box2d/build --config Release --target install
