name: build
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:

  build_simple_with_pixi:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      ################################################################
      # SETUP
      ################################################################
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: v0.39.2
      - run: |
          pixi run build-box2d
          pixi run install
          pixi run test
